# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: skienzle <skienzle@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/09/19 13:46:35 by skienzle          #+#    #+#              #
#    Updated: 2021/09/19 13:49:42 by skienzle         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc main.c -framework OpenGL -framework AppKit -Wall -Wextra -Lminilibx -lmlx